# Dockerfile for OPC UA Server
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 4840
CMD [ "node", "server.js" ]